apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: db-ns
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: employees-db:1.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: empuser
        - name: MYSQL_PASSWORD
          value: emppass
      ports:
        - containerPort: 3306
