apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-web
  namespace: web-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: web
          image: image: 654654194559.dkr.ecr.us-east-1.amazonaws.com/employees-web:1.1
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: mysql.db-ns.svc.cluster.local
            - name: DBUSER
              value: empuser
            - name: DBPWD
              value: emppass
            - name: DATABASE
              value: employees
            - name: DBPORT
              value: "3306"
